version: "3.7"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/var/www/static
    entrypoint:
      - ./entrypoint.sh
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
    depends_on:
      - web
      - postgresql
